services:
  composer_install:
    image: composer:2
    working_dir: /var/www/server
    command: composer install --no-interaction --prefer-dist --no-progress
    volumes:
      - ./server:/var/www/server

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./server:/var/www/server
    depends_on:
      - composer_install
      - db

  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camagru
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
